version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrosync-webapp
    ports:
      - "8880:8880"
    environment:
      VITE_APP_PORT: ${VITE_APP_PORT}
      VITE_BACKEND_API_URL: ${VITE_BACKEND_API_URL}
      VVITE_MQTT_USERNAME: ${VVITE_MQTT_USERNAME}
      VITE_MQTT_PASSWORD: ${VITE_MQTT_PASSWORD}
